language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
env: DJANGO_SETTINGS_MODULE="static_precompiler.tests.django_settings"
install:
  - pip install django
  - pip install coveralls
script:
  converage run --source=static_precompiler setup.py test
after_success:
  coveralls
