language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install django
# command to run tests, e.g. python setup.py test
script:
  - export DJANGO_SETTINGS_MODULE="static_precompiler.tests.django_settings"
  - python setup.py test
