language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
env: DJANGO_SETTINGS_MODULE="static_precompiler.tests.django_settings"
before_install:
  - npm install -g coffee-script
  - npm install -g less
  - gem install sass --version 3.2.18
  - gem install compass
install:
  - pip install coveralls
  - pip install django
  - pip install six
  - pip install mock
script:
  coverage run --source=static_precompiler setup.py test
after_success:
  coveralls
